version: '3.8'

services:
  faceit_app:
    build: .
    container_name: faceit_app
    env_file:
      - .env
    depends_on:
      - faceit_db
    ports:
      - "5051:5050"
    restart: unless-stopped

  faceit_db:
    image: mysql:8.0
    container_name: faceit_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: faceit_db
    ports:
      - "3308:3306"
    volumes:
      - faceit-db:/var/lib/mysql

  second_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: faceit_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: faceit_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - faceit_db

  php:
    image: php:8.2-apache
    container_name: faceit_php
    ports:
      - "8889:80"
    volumes:
      - ./faceit_php:/var/www/html
    depends_on:
      - faceit_app

volumes:
  faceit-db: