version: '3.8'

services:
  fun-zone:
    build: .
    container_name: faceit_app
    env_file:
      - .env
    depends_on:
      - faceit-db
    image: ds
    restart: unless-stopped

  faceit-db:
    image: mysql:8.0
    container_name: faceit_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: faceit_db
    ports:
      - "3308:3306"
    volumes:
      - funzone_db:/var/lib/mysql

  second_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: faceit_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: second_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - second_db

  php:
    image: php:8.2-apache
    container_name: faceit_php
    ports:
      - "8889:80"
    volumes:
      - ./faceit_php:/var/www/html
    depends_on:
      - fun-zone

volumes:
  funzone_db: